### ISSUE TITLE
这个插件是否只能运行在集客的固件上面？

### ISSUE THREAD

**Issue by Cainfish** [lwb1978/openwrt-gecoosac#1]
如题，请问此插件是否只能运行在集客的固件上面？

**Comment by lwb1978** [comment]
说明包括仓库名都写得清清楚楚了，是openwrt插件，运行在openwrt上，如果你不知道openwrt是啥，那这个仓库里的插件对你没用。

**Comment by Cainfish** [comment]
感谢您的解答，已经搞定了，实在不好意思。
